GET http://localhost:3000/

###
GET http://localhost:3000/abc_xyz

### register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "T@gmail.com",
    "password": "123"
}

### login route
POST http://localhost:3000/auth/login

### refresh-toekn route
POST http://localhost:3000/auth/refresh-token

### logout toute
DELETE http://localhost:3000/auth/logout